name: Caller Push Workflow

on:
  push:
    branches:
      - main  

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-push-workflow.yml
    with:
      branch: ${{ github.ref }}
      commit_message: ${{ github.event.head_commit.message }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
