name: Caller Push Workflow

on:
  push:
    branches:
      - main  

jobs:
  call-reusable-workflow:
    uses: Sneha261996/workflow-triggers/.github/workflows/reusable-push-workflow.yml@main  
    with:
      branch: ${{ github.ref }}
      commit_message: ${{ github.event.head_commit.message }}
